baseURL = "https://timfei.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Wenwei Fei"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
